---
- hosts: all
  sudo: yes
  tasks:
  - name: update os
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"
  - name: install apache
    apt:
      name: apache2
      state: present
    notify:
    - restart apache 
    when: ansible_os_family == "Debian"
  - name: intall packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php 
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
    notify:
    - retsart apache 
    when: ansible_os_family == "Debian"
  handlers:
  - name: restart apache
    service:
      name: apache2
      enabled: yes
      state: restarted
    when: ansible_os_family == "Debian"