---
- hosts: all
  sudo: yes
  gather_facts: False
  tasks:
  - name: install apache
    apt:
      name: apache2
      state: present
    notify:
    - restart apache
  - name: Delete index.html page
    file:
      state: absent
      path: /var/www/html/index.html
  - name: Download index.html page 
    get_url:
      url: https://raw.githubusercontent.com/srinum0464/projecttest/ansible/index.html
      dest: /var/www/html/index.html
      mode: '0777'
  - name: intall packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php 
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
    notify:
    - restart apache 
  handlers:
  - name: restart apache
    service:
      name: apache2
      enabled: yes
      state: restarted