---
- hosts: all
  sudo: yes
  gather_facts: False
  tasks:
  - name: "Auto ssh login"
    command: 
  - name: install apache
    apt:
      name: apache2
      state: present
    register: find_output
    notify:
    - restart apache 
    when: ansible_os_family == "Debian"
  - debug:
      var: find_output
  - name: intall packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php 
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
    notify:
    - restart apache 
    when: ansible_os_family == "Debian"
  handlers:
  - name: restart apache
    service:
      name: apache2
      enabled: yes
      state: restarted
    when: ansible_os_family == "Debian"